lynx-family/debug-router

- .github/workflows/ci.yml
- .tools_shared
- CONTRIBUTING.md
- DEPS
- test/connect_test/check_android_connection_ci.py
- test/unit_test/check_android_unittest.py
- test/unit_test/check_test_build.py
- test/unit_test/check_test_run.py
- test/unit_test/lynx_env.py
- test/unit_test/run_unittests.py
- tools/android_tools/android_env.sh
- tools/android_tools/emu_bootup.sh
[Testing][Doc] Add full CI tasks for debug-router 
1. Add full CI checks.
a. simple cpp unittest check
b. android and ios unittest check
c. android websocket and usb cnnection check for debug-router-connector usgae.
2. Improve the CONTRIBUTING.md due to the test completion.
> [Testing] Add full CI tasks for debug-router

- debug_router/native/socket/usb_client.cc
- debug_router/native/socket/work_thread_executor.cc
- debug_router/native/socket/work_thread_executor.h
[BugFix] Fix multiple thread problems in work_thread_executor.cc
1. Replace work_mutex with task_mutex in the shutdown method.
2. Reduce the locking granularity of the task_mutex in the shutdown method.
issue: #17
> [BugFix] Fix multiple thread problems in work_thread_executor.cc

- debug_router/native/base/socket_guard.h
- debug_router/native/net/websocket_client.cc
- debug_router/native/net/websocket_client.h
1. use work_thread_ to handle websocket_client main task rather than manually lock() and unlock().
2. use SocketGuard to manage socket_fd_.
issue:#23
> [Optimize] Optimize  Websocket Client

- debug_router/iOS/DebugRouter.mm
[str UTF8String] will cause crash when str is nil, so we add judgement to avoid crash.
> [BugFix][iOS]Fix App crash when nil is considered as NSString

- debug_router/native/net/websocket_task.cc
If the connect function has not succeeded, socket_guard_ may still be nullptr, and socket_guard_.Get() will cause the crash.
> [BugFix]Fix crash that socket_guard_ maybe nullptr

- debug_router/native/net/websocket_task.cc
- debug_router/native/net/websocket_task.h
- debug_router/native/socket/socket_server_api.cc
- debug_router/native/socket/usb_client.cc
- debug_router/native/socket/usb_client.h
- debug_router/native/socket/work_thread_executor.cc
- debug_router/native/socket/work_thread_executor.h
1. fix do_read crash caused by multithreaded operation of the socket_guard_.
2. fix crash that run() thread can not be released by the destructor when work_thread_executor destructor.
3. add worker->get_id() to determine whether the current waiting thread is this thread, if so, detach.
> [BugFix]Fix all the crash that caused by thread processing

- debug_router/native/socket/work_thread_executor.cc
Solve the problem that debug-router fails to compile when Lynx turns on no-exception.
> [Optimize]Add __cpp_exceptions judgement for no-exception

- debug_router/native/net/websocket_client.cc
- debug_router/native/net/websocket_task.cc
- debug_router/native/net/websocket_task.h
- debug_router/native/socket/posix/socket_server_posix.cc
- debug_router/native/socket/usb_client.cc
- debug_router/native/socket/usb_client.h
- debug_router/native/socket/work_thread_executor.cc
- debug_router/native/socket/work_thread_executor.h
1. start thread after constructor
2. add weak_ptr to verify whether the class is been destroyed.
> [BugFix] Fix crash of worker_thread_executor

- debug_router/native/base/socket_guard.h
- debug_router/native/socket/usb_client.cc
- debug_router/native/socket/usb_client.h
Using WorkThreadExecutor can conveniently stop all threads of usb_client when it ends, avoiding unexpected resource access.
issue: #46
> [BugFix][android][ios][common] Use work_thread_executor instead of raw thread

- debug_router/native/socket/posix/socket_server_posix.cc
- debug_router/native/socket/socket_server_api.cc
- debug_router/native/socket/socket_server_api.h
A UsbClient must call stop() before destruction to prevent threads from accessing its resources after it's destroyed.
issue: #42
> [BugFix][android][ios][common] Fix thread crash that occurs when calling worker.join() during WorkThreadExecutor shutdown.

- debug_router/native/base/socket_guard.h
- debug_router/native/socket/socket_server_api.cc
- debug_router/native/socket/usb_client.cc
- debug_router/native/socket/usb_client.h
1. add LOG for Usbclient stop.
2. add unique_ptr for payload to deal with huge message.
> [BugFix]Fix crash that occurs when transferring a huge message via USB.

- test/connect_test/check_android_connection_ci.py
- test/e2e_test/connector_test/large_message_test.js
use large message to test USBClient::Read.
> [Testing] Add USB e2e test for the crash that occurs when receiving large messages.

- debug_router/native/protocol/md5.cc
> [Optimize]Fix build warning for sprintf is deprecated

- debug_router/native/protocol/md5.cc
use 33 - i * 2 instead of 33 to execute snprintf.
> [BugFix]Fix that snprintf may cause crash

- debug_router/native/core/debug_router_core.cc
- debug_router/native/core/debug_router_core.h
1. add judgement to avoid crash.
2. use another way to iterate over state_listeners_.
3. add state_listeners_mutex_ to lock the process to state_listeners.
> [BugFix]  Fix thread safety issues when iterating over state_listeners_.

- debug_router/native/core/debug_router_core.cc
When the OnOpen function is not used to assign a value to current_transceiver_, nullptr will cause current_transceiver_->GetType() to crash.
> [BugFix]Fix that current_transceiver_ maybe nullptr

- debug_router/native/core/debug_router_core.cc
Move the assignment position of the is_first_connect_ variable.
> [Optimize]Fix reporting issues caused by incorrect variable assignment

- debug_router/native/socket/win/socket_server_win.cc
Remove the logic causing port reuse to fix the problem of multiple Windows apps being unable to connect to DebugRouterConnector simultaneously.
> [BugFix] Resolve the issue where multiple Windows apps cannot connect to DebugRouterConnector

- debug_router/native/net/websocket_task.cc
The Windows getaddrinfo return value format differs from POSIX, so differentiating the processing based on macro definitions fixes Windows build issues.
> [BugFix]Fix inappropriate return value judgment.

- .github/workflows/npm-manual-release.yml
- .github/workflows/remote-debug-driver-publish-npm.yml
Enable OIDC publishing to make it easier and more secure to publish npm packages from CI.
See:
https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
https://docs.npmjs.com/trusted-publishers
> [Optimize]Enable trusted publishing for npm packages
